version: 2
jobs:
  deploy:
    machine:
      enabled: true
    steps:
      - add_ssh_keys:
          fingerprints:
            - "3f:e9:ee:a1:88:05:be:c4:59:74:26:18:8e:16:ad:65" #上記メモったハッシュを指定
      - run: ssh -p $SSH_PORT $SSH_USER@$SSH_HOST "sudo ~/deploy-me.sh"
 
workflows:
  version: 2
  deploy:
    jobs:
      - deploy:
          filters:
            branches:
              only: master