default: &default
  adapter: mysql2
  encoding: utf8
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: <%= ENV['DATABASE_USER'] %>
  password: <%= ENV['DATABASE_PASSWORD'] %>
  database: nomadcafe_production
  socket: /var/lib/mysql/mysql.sock
  host: localhost
development:
  <<: *default
  database: nomadcafe_development
  #socket: /tmp/mysql.sock
test:
  <<: *default
  database: nomadcafe_test
production:
  << : *default






# default: &default
#   adapter: mysql2
#   encoding: utf8
#   pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
#   username: root
#   password: password
#   socket: /tmp/mysql.sock
#   host: localhost

# development:
#   <<: *default
#   database: nomadcafe_development

# test:
#   <<: *default
#   database: nomadcafe_test

# production:
#   database: nomadcafe_production
#   username: root
#   password: <%= ENV['DATABASE_PASSWORD'] %>
#   socket: /var/lib/mysql/mysql.sock
#   host: localhost